Fix Radix Param, nested ternary, expected '===', console.log
foyzulkarim/mern-boilerplate pull request #35
Opened 2022-03-02 15:08 UTC by abidr

#34 Issue
- Fixed Radix parameters error
- Changed nested ternary to regular expression
- changed == to === for type check
- Ignored console.log (it might be needed)

2022-03-02 20:45 UTC, foyzulkarim requested changes
Thanks brother. I added some suggestion. Please have a look. :)

2022-03-02 20:45 UTC, foyzulkarim commented on server/src/services/product-service.js
> +  }
How about this?
```
let query = {};
if(queries.length === 1) {
    // code
}
if(queries.lengh > 1){
    // code 
}

```

2022-03-02 20:45 UTC, foyzulkarim commented on server/src/services/product-service.js
> +  }
same suggestion as above.

2022-03-04 14:05 UTC, foyzulkarim commented
@abidr brother, do you want to work on this anytime soon?

2022-03-04 14:26 UTC, abidr commented
> @abidr brother, do you want to work on this anytime soon?

Yes I'll make the changes today.

2022-03-05 07:06 UTC, foyzulkarim commented
this pull request is obsolete now. closing it. thanks for your efforts

2022-03-05 07:06 UTC, closed without merging